--- 1 EXPLORE DATABASE
--- Explore All Objects in the Database
SELECT * FROM INFORMATION_SCHEMA.TABLES

--- Explore All Columns in the Database
SELECT * FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'dim_customers'

--- 2 DIMENSION EXPLORATION
SELECT DISTINCT country FROM [gold].[dim_customers]
SELECT DISTINCT marital_status FROM [gold].[dim_customers]
SELECT DISTINCT gender FROM [gold].[dim_customers]

/*
customer_key
customer_id
customer_number
first_name
last_name
country
marital_status
gender
birthdate
create_date
*/


SELECT DISTINCT product_name FROM [gold].[dim_products]
SELECT DISTINCT category FROM [gold].[dim_products]
SELECT DISTINCT subcategory FROM [gold].[dim_products]

--- 3 DATE EXPLORATION

SELECT MIN ([order_date]), MAX([order_date]), DATEDIFF(YEAR, MIN ([order_date]), MAX([order_date])) FROM [gold].[fact_sales]
SELECT MIN ([shipping_date]), MAX([shipping_date]) FROM [gold].[fact_sales]
SELECT MIN ([due_date]), MAX([due_date]) FROM [gold].[fact_sales]

--- Find the youngest andthe older customer

SELECT 
MIN ([birthdate]) AS oldest,
DATEDIFF(YEAR, MIN ([birthdate]), GETDATE()) AS age,
MAX([birthdate]) AS youger,
DATEDIFF(YEAR, MAX ([birthdate]), GETDATE()) AS age
FROM [gold].[dim_customers]


--- 4 MEASURES EXPLORATION
--- Find the total sales
SELECT
SUM([sales_amount])
FROM [gold].[fact_sales]

--- Find how many items are sold
SELECT
SUM([quantity])
FROM [gold].[fact_sales]

--- Find the average selling price
SELECT
AVG([price])
FROM [gold].[fact_sales]

--- Find the total number of Orders
SELECT
COUNT([order_number])
FROM [gold].[fact_sales]

SELECT
COUNT(DISTINCT([order_number]))
FROM [gold].[fact_sales]

--- Find the total number of Products
SELECT
COUNT([product_key])
FROM [gold].[dim_products]

SELECT
COUNT(DISTINCT([product_key]))
FROM [gold].[dim_products]

--- Find the total number of Customers
SELECT
COUNT(DISTINCT([customer_key]))
FROM [gold].[dim_customers];

--- Find the total number of customers that has placed an order
SELECT COUNT(DISTINCT([customer_key])) FROM [gold].[fact_sales];
-----------------------------------------------------------------------------------
--- Generate a Report that shows all key metrics of the business

SELECT 'Total Sales' as measure_name, SUM([sales_amount]) AS measure_value FROM [gold].[fact_sales]
UNION ALL
SELECT 'Total Quantity' as measure_name, SUM([quantity]) AS measure_value FROM [gold].[fact_sales]
UNION ALL
SELECT 'Average Price' as measure_name, AVG([price]) AS measure_value FROM [gold].[fact_sales]
UNION ALL
SELECT 'Total Nr. Orders' as measure_name, COUNT(DISTINCT([order_number])) AS measure_value FROM [gold].[fact_sales]
UNION ALL
SELECT 'Total Nr. Products' as measure_name, COUNT(DISTINCT([product_key])) AS measure_value FROM [gold].[dim_products]
UNION ALL
SELECT 'Total Nr. Customers' as measure_name, COUNT(DISTINCT([customer_key])) AS measure_value FROM [gold].[dim_customers]

--- 5 MAGNITUDE

--- Find total customers by countries
SELECT country, COUNT(customer_key) as customers FROM [gold].[dim_customers] GROUP BY country ORDER BY COUNT(customer_key) DESC;

--- Find total customers by gender
SELECT gender, COUNT(customer_key) as customers FROM [gold].[dim_customers] GROUP BY gender ORDER BY COUNT(customer_key) DESC;

--- Find total products by category
SELECT category, COUNT(product_key) as products FROM [gold].[dim_products] GROUP BY category ORDER BY COUNT(product_key) DESC;

--- What is the average costs in each category?
SELECT category, AVG([product_cost]) as average_cost FROM [gold].[dim_products] GROUP BY category ORDER BY AVG([product_cost]) DESC;

--- What is the total revenue generated for each category?
SELECT T2.category, SUM(T1.[sales_amount]) as total_revenue 
FROM [gold].[fact_sales] T1
LEFT JOIN [gold].[dim_products] T2 ON T1.product_key = T2.product_key
GROUP BY T2.category 
ORDER BY total_revenue DESC;

--- Find total revenue is generated by each customer
SELECT T2.customer_key, T2.first_name, T2.last_name, SUM(T1.[sales_amount]) as total_revenue 
FROM [gold].[fact_sales] T1
LEFT JOIN [gold].[dim_customers] T2 ON T1.customer_key = T2.customer_key
GROUP BY T2.customer_key, T2.first_name, T2.last_name
ORDER BY total_revenue DESC;

--- What is the distribution of sold items across countries?
SELECT T2.country, SUM(T1.[quantity]) as total_sold_items
FROM [gold].[fact_sales] T1
LEFT JOIN [gold].[dim_customers] T2 ON T1.customer_key = T2.customer_key
GROUP BY T2.country 
ORDER BY total_sold_items DESC;

--- 6 RANKING ANALYSIS
--- Which 5 products generate the highest revenue?
SELECT TOP 5 T2.product_name, SUM(T1.[sales_amount]) as highest_revenue
FROM [gold].[fact_sales] T1
LEFT JOIN [gold].[dim_products] T2 ON T1.product_key = T2.product_key
GROUP BY T2.product_name 
ORDER BY highest_revenue DESC;

-- window function row_number
SELECT *
FROM (
	SELECT 
	T2.product_name, 
	SUM(T1.[sales_amount]) as highest_revenue,
	ROW_NUMBER() OVER (ORDER BY SUM(T1.[sales_amount]) DESC) AS rank_products
	FROM [gold].[fact_sales] T1
	LEFT JOIN [gold].[dim_products] T2 ON T1.product_key = T2.product_key
	GROUP BY T2.product_name ) T3
WHERE rank_products <= 5
;

-- window function rank
SELECT *
FROM (
	SELECT 
	T2.product_name, 
	SUM(T1.[sales_amount]) as highest_revenue,
	RANK() OVER (ORDER BY SUM(T1.[sales_amount]) DESC) AS rank_products
	FROM [gold].[fact_sales] T1
	LEFT JOIN [gold].[dim_products] T2 ON T1.product_key = T2.product_key
	GROUP BY T2.product_name ) T3
WHERE rank_products <= 5
;


--- What are the 5 worst-performing products in terms of sales?
SELECT TOP 5 T2.product_name, SUM(T1.[sales_amount]) as lowest_revenue
FROM [gold].[fact_sales] T1
LEFT JOIN [gold].[dim_products] T2 ON T1.product_key = T2.product_key
GROUP BY T2.product_name 
ORDER BY lowest_revenue;

--- Which 5 subcategory generate the highest revenue?
SELECT TOP 5 T2.subcategory, SUM(T1.[sales_amount]) as highest_revenue
FROM [gold].[fact_sales] T1
LEFT JOIN [gold].[dim_products] T2 ON T1.product_key = T2.product_key
GROUP BY T2.subcategory 
ORDER BY highest_revenue DESC;

--- Find the top 10 customers who have generated the highest revenue
SELECT TOP 10 
T2.customer_key,
T2.first_name,
T2.last_name,
SUM(T1.[sales_amount]) as total_revenue
FROM [gold].[fact_sales] T1
LEFT JOIN [gold].[dim_customers] T2 ON T1.customer_key = T2.customer_key
GROUP BY T2.customer_key,
T2.first_name,
T2.last_name
ORDER BY total_revenue DESC;

--- Find 3 customers with the fewest orders placed
SELECT TOP 3 
T2.customer_key,
T2.first_name,
T2.last_name,
COUNT(DISTINCT(T1.[order_number])) as orders_placed
FROM [gold].[fact_sales] T1
LEFT JOIN [gold].[dim_customers] T2 ON T1.customer_key = T2.customer_key
GROUP BY T2.customer_key,
T2.first_name,
T2.last_name
ORDER BY orders_placed;
